---
title: Matthew Blode
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: work
  values:
    layout: post
    permalink: "/work/:title/"
sass:
  style: compressed
permalink: pretty
